version: '3.4'

services:
    
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_DATABASE=true_code
            - MYSQL_USER=user
            - MYSQL_PASSWORD=12345
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306
        expose:
            - "3306"

    rabbit-server:
        image: rabbitmq:3-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=user
        ports:
            - 5672:5672
            - 15672:15672
        expose:
            - "5672"
            - "15672"